### ISSUE TITLE
How to handle environment-specific settings

### ISSUE THREAD

**Issue by martijnv** [kraftwagen/skeleton#3]
In our projects we are accustomed to use a folder per environment within the Drupal sites folder to have specific settings per environment. For example: we disable the caches in the settings.php in dev.example.com, but enable them in the settings.php for acc.example.com and www.example.com.

It seems that Kraftwagen can only handle one settings.php that it links from the sites/default folder.

Is there a Kraftwagen-specific way to handle environment-specific settings?

**Comment by rolfvandekrol** [comment]
Kraftwagen copies `settings.php` and `settings.local.php` from the `cnf` folder in your `src` to your `cnf` directory when you run `drush kw-setup`. In this `settings.local.php` file you can specify local (environment specific) settings. If you prefer to keep some settings per environment in version control, you can add some more variants of `settings.*.php` to the `cnf` directory. In this case Kraftwagen won't be able to pick the correct files anymore, so you need to run the steps of `kw-setup` manually, execute some manual labor after running `kw-setup`, or write your own Drush extension that manages your settings files the way you like.

**Comment by martijnv** [comment]
I like the fact that we are currently able to put environment settings in version control by using separate folders within sites/ for each environment. I might look into adapting the kraftwagen scripts to support this.
