### ISSUE TITLE
Location of files folder

### ISSUE THREAD

**Issue by martijnv** [kraftwagen/skeleton#4]
Kraftwagen symlinks the files folder in the sites/default folder. For aesthetic reasons we put the files folder in the docroot of the site (nicer URL's for files). Is this possible with Kraftwagen? In other words: can you tell Kraftwagen to symlink the files folder from somewhere else?

**Comment by rolfvandekrol** [comment]
Currently there is no way to say that to Kraftwagen, without writing your own Drush extension. We'll consider this a feature request. Could you please file it under the http://github.com/kraftwagen/kraftwagen repository?

**Comment by martijnv** [comment]
I've created a feature request in the kraftwagen/kraftwagen repository: https://github.com/kraftwagen/kraftwagen/issues/1
