### ISSUE TITLE
How to handle Skeleton updates

### ISSUE THREAD

**Issue by martijnv** [kraftwagen/skeleton#5]
I may misunderstand Kraftwagen on this point, but how do you handle updates to the Skeleton?

From what I understand the Skeleton replaces the install profile in the way we use it until now. Which was: If there is a contrib module update, we update the install profile and then update all projects using that install profile by overwriting the previous version of the install profile.

When you use Kraftwagen and you have an update for the Skeleton (for instance also a contrib module update). Wouldn't it overwrite project-specific changes in for instance the .make file? Or should you use the build.make.tpl.php file for generic Skeleton things and the <project>.make file for project-specific things?

**Comment by rolfvandekrol** [comment]
After you created a project from a skeleton, there is no connection between the project and the skeleton anymore. Updates in the skeleton won't affect the project. If something changes in the skeleton that you think should also be applied to your projects, you will have to do that manually (or find some way to automate that a little).

**Comment by barraponto** [comment]
Right now, it exports all the code from the skeleton git repo, changing some `***variables***`. If it cloned the git repo, then changed the variables and commited that change, we'd keep the commit history. And then we'd be able to rebase, incorporating changes to the skeleton.

Although I don't see a lot of advantages in keeping up with a skeleton...
