### ISSUE TITLE
Question about presence of modules in the .make file of the example skeleton

### ISSUE THREAD

**Issue by martijnv** [kraftwagen/skeleton#6]
Why are there modules in the .make file of the skeleton that are not enabled by the install profile (i.e.: pathauto, token)?

**Comment by rolfvandekrol** [comment]
The current published skeleton should not be considered a finished product, but more like a inspiration how to create your own skeleton repository.

**Comment by martijnv** [comment]
Ok, I thought as much but wanted to make sure that I didn't miss something somewhere :).
