### ISSUE TITLE
How to handle custom module/theme development

### ISSUE THREAD

**Issue by martijnv** [kraftwagen/skeleton#7]
How do you envisage custom module/theme development in a project that is set up with Kraftwagen?

A developer needs their custom code to run in a working Drupal environment to unittest and debug, but the Kraftwagen way of handling code is by putting it in the src folder (from what I understand). If you do that, then you have to build the project everytime you have written some code and want to test it out. 

What is your vision/working method for this? DO you do something with temporary symlinks or do you work on code in the buildtree and copying it back and forth to/from the sourcetree?

**Comment by rolfvandekrol** [comment]
We actively develop in the build tree. If you use git, then the `profiles/PROJECT` directory is also a Git repository in which you can create commits. Sometimes we directly push from this directory, sometimes we run `git pull ../build/profiles/PROJECT` from the `src` to get the commits.

**Comment by martijnv** [comment]
Ah, I did not realise the profiles/PROJECT folder was also a GIT repository. I figured that the build folder would be a copy without any version control artefacts like the .git folder. I wonder if it is desirable to have these in the build folder that is also deployed to a production environment?

It does provide a solution for development though since you can indeed commit and push/pull then. Maybe the fact that the .git information is retained when building should be dependent on the environment variable?

**Comment by rolfvandekrol** [comment]
I personally do not think that should be controlled by the environment. For Kraftwagen in the core the words 'production' and 'development' mean nothing and i think it should stay that way. In the capistrano integration that we are developing, we use the export command on the version control system, which essentially makes sure that the `src` is not a repository (anymore) when we start the build process.

**Comment by martijnv** [comment]
Ah right. That sounds like a good solution too. That's how we handle deployments with Jenkins at the moment as well.
